#!/bin/Rscript
install.packages(c('devtools','remotes','car'))
install.packages("BiocManager")
BiocManager::install("dada2", version = "3.16") 
remotes::install_version('ggplot2','3.5.1',repos='http://cran.us.r-project.org') 
BiocManager::install('phyloseq') 
remotes::install_version('vegan','2.6-8',repos='http://cran.us.r-project.org') 
remotes::install_version('lubridate','1.9.3',repos='http://cran.us.r-project.org') 
remotes::install_version('dplyr','1.1.4',repos='http://cran.us.r-project.org') 
remotes::install_version('tidyverse','2.0.0',repos='http://cran.us.r-project.org') 
remotes::install_version('ggpubr','0.6.0',repos='http://cran.us.r-project.org') 
#remotes::install_version('rstatix','0.7.2',repos='http://cran.us.r-project.org') 
#remotes::install_version('stringr','1.32.0',repos='http://cran.us.r-project.org') 
devtools::install_github("thomasp85/patchwork",ref="v1.3.0") 
remotes::install_github("gavinsimpson/ggvegan")
devtools::install_github("IRkernel/IRkernel") 
IRkernel::installspec(user = FALSE)
remotes::install_version('Matrix','1.6',repos='http://cran.us.r-project.org')
remotes::install_version('rstatix','0.7.2',repos='http://cran.us.r-project.org')
remotes::install_version('stringr','1.5.1',repos='http://cran.us.r-project.org')
